### PR TITLE
INSTALLATION.md: use correct Hubble image

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by youssefazrak** [comment]
Hey @tklauser would be great to have it also on the UI activation command here `cilium hubble enable --ui`---> `cilium hubble enable --relay-version -service-mesh:v1.11.0-beta.1 --ui`

**Comment by tklauser** [comment]
Thanks @youssefazrak! Now updated the `cilium hubble enable --ui` command as well.

**Comment by tklauser** [comment]
This used to work with cilium-cli v0.10.0 without specifying `--relay-version`, so this is really a regression in cilium-cli v0.10.1.

Not sure whether we still want to merge this PR as a temporary solution to prevent service mesh beta users from hitting issues until we've fixed cilium-cli and released a new version?

**Comment by tklauser** [comment]
Closing this in favor of https://github.com/cilium/cilium-cli/pull/694 which will fix the underlying issue in cilium-cli.

**Pull request closed without merging**
